<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Test\Form\ViewModel\Form $form
 */
$form = $block->getData('form');
?>

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $form->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend">
                    <span><?= $block->escapeHtmlAttr(__('Write me')) ?></span>
                </legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">

                        <div class="field name required">
                            <label class="label" for="title">
                                <span><?= $block->escapeHtmlAttr(__('Email')) ?></span>
                            </label>
                            <div class="control">
                                <input name="email"
                                       id="email"
                                       title="Email"
                                       value=""
                                       class="input-text"
                                       type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>

                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save">
                        <span><?= $block->escapeHtmlAttr(__('Send')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
